Kentico/KInspector

- KInspector.Modules/KInspector.Modules.csproj
- KInspector.Modules/Modules/General/MediaLibraryAzureLimitModule.cs
- KInspector.Modules/Scripts/MediaLibraryAzureLimitModule.sql
Based on the issue #24 
I've trimmed file name from the file path and grouped those records together 
(e.g.: ```/somefolder/subfolder/filename.ext``` -> ```/somefolder/subfolder```)
All records having more than 100 rows are displayed to the user for further actions.
Anything to improve? Thanks
> Add module checking media library limits in Azure

- KInspector.Core/DatabaseService.cs
- KInspector.Modules/Modules/General/DatabaseConsistencyCheckModule.cs
Method ExecuteAndGetTable new returns empty DataTable
if there is no output from the SQL Server. That means
there is no need for try/catch in
DatabaseConsistencyCheckModule.
Our implementation threw an exception if there was no
output from SQL Server. It was caused because there was
no check for table existence in DataSet.
> Get rid of TODO in DatabaseConsistencyCheckModule

- .gitignore
- build.cmd
- build.fsx
I've added a very simple [FAKE](http://fsharp.github.io/FAKE/) build script to simplify the use of the analyzer tool. Just run `build.cmd` and get the artifacts without starting Visual Studio or something else.
> Add a simple FAKE build script

- KInspector.Modules/KInspector.Modules.csproj
- KInspector.Modules/ProbeData/CMSPages/KInspectorProbe.aspx.cs
- KInspector.Modules/ProbeData/CMSPages/KInspectorProbe.aspx.designer.cs
When running the `General` -> `Cache items` module an exception was thrown because the namespaces were not matching:
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
at System.Net.HttpWebRequest.GetResponse()
at KInspector.Modules.Modules.General.CacheItemsModule.GetResults(InstanceInfo instanceInfo, DatabaseService dbService) in c:\Projects\KInspector\KInspector.Modules\Modules\General\CacheItemsModule.cs:line 34
> Adjust namespace in `KInspectorProbe.aspx`

- KInspector.Modules/Modules/EventLog/PageNotFoundsModule.cs
Add hint that they can use external services
to check the whole website for the broken links 
as mentioned in issue #3
> Improve 'Non found errors' module description

- KInspector.Core/InstanceInfo.cs
- KInspector.Tests/InstanceInfoTests.cs
- KInspector.Tests/Kentico.KInspector.Tests.csproj
Fix for the issue #57 
Sometimes the website is running under virtual path and the URL looks like this ```http://localhost/kentico8```
Some modules (RobotsTxtModule, CacheItemsModle, ...) try to append the relative path to the base URL but without trailing slash, the relative path is replaced.
E.g.:
```
var uri = new Uri("http://localhost/kentico8");
new Uri(uri, "robots.txt"); // http://localhost/robots.txt
```
With trailing slash, the relative path is appended as expected.
```
var uri = new Uri("http://localhost/kentico8/");
new Uri(uri, "robots.txt"); // http://localhost/kentico8/robots.txt
```
> Fix support for virtual path URLs

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/Content/DuplicatePageAliasesModule.cs
- KInspector.Modules/Scripts/DuplicatePageAliasesModule.sql
> Created a module to detect Duplicate Page Aliases

- KInspector.Modules/Modules/Security/PasswordPolicyModule.cs
- KInspector.Modules/Scripts/PasswordPolicy.sql
- KInspector.Tests/Modules/Security/PasswordPolicyModuleTests.cs
Made modifications to PasswordPolicyModule and PasswordPolicy DB script to account for multiple sites.
This fix also accounts for the access to DataTable elements by "ColumnName" rather than by index, [x].
Finally, corresponding unit tests for the PasswordPolicyModule were reviewed (optimized) somewhat.
> PasswordPolicyModule changes to Fix #17 

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/Content/WebPartColumnsModule.cs
- KInspector.Modules/Scripts/WebPartColumnsModule9.sql
Added support for use of Unspecified Column Support Module to be used on Kentico 9. Modified existing sql script to work with K9's new format for webpart storage in the DB. Also removed check for wireframes since wireframes no longer exist in K9.
> K9 unspecified column support

- KInspector.Web/FrontEnd/Scripts/Directives.js
- KInspector.Web/FrontEnd/index.html
…he module
Currently, in order to see the details of what a module does, you have to Load the Module, executing its behavior. This is problematic because first-time users won't have the context of what the modules do in order to know which module they want to run. This commit adds a button "Show Comments" that displays the comments separately from the results. In order to do this without also displaying the "results", I had to remove the Results toggle from the header bar, and place it directly on the Toggle arrow and the Header text. No other changes to existing functionality were needed.
> Display module description separately from running the module

- KInspector.Modules/Scripts/Setup/GlobalAdminSetupModule.sql
Fixes edge-case where global admin account is immediately locked if
password expiration is enabled, account locking is set, and the global
admin last changed the password earlier than the expiration window.
> Add reset to password expiration for global admin reset module

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/Content/DBFileConsistencyModule.cs
- KInspector.Modules/Scripts/GetLibraryAndAttachmentFiles.sql
This module adds three checks to the system:
1) Media Library records not associated with any file in the filesystem.
- This iterates over the media library and attempts to access the physical file for each. It then displays each record that was not found. This way the user can go find the missing file and re-add it if necessary.
2) Form Attachments records not associated with any file in the filesystem.
- This iterates over each bizform and finds any user-submitted attachments submitted. If Kentico believes one should exist, but the file is not in the file system, that record is returned and reported. This allows the owner to find any missing attachments that the user expects to have been submitted.
3) Form Attachments files not associated with any Form record in Kentico
- This iterates …
> Media file consistency module

- KInspector.Modules/Modules/Content/DBFileConsistencyModule.cs
- KInspector.Modules/Scripts/GetLibraryAndAttachmentFiles.sql
This was causing a sql error that kept terminating the function. A check on the length of the sql query fixes this.
> If the site had no forms, this script would sql underflow at the end

- KInspector.Modules/Modules/Content/SiteTemplatesModule.cs
- KInspector.Modules/Scripts/SiteTemplatesModule-Templates.sql
Resolves #129 by updating the name and description of the module, adding the template display name to the table headers, and provides more info when a template has no web part zones or a zone has no web parts.
> Page template names

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/General/TaskProcessingIssuesModule.cs
- KInspector.Modules/Scripts/TaskProcessingIssueModule.sql
This module checks to see if various task tables have records older than 24hr. still in them. It throws a warning if at least one has some tasks.
> Adds a generic task processing issues module

- KInspector.Modules/Modules/General/ClassTableValidation.cs
When running the class table validation in versions earlier than version 10, it would error out because the string.Join() had an empty string to join which later caused an invalid SQL query.
> Added logic to check for empty string within the IN() query.

- KInspector.Modules/Modules/Security/SecurityAppSettingsModule.cs
Adds a check in SecurityAppSettingsModule.cs for CMSEnableCsrfProtection variable in configuration
Fixes #172
> Add a check for CMSEnableCsrfProtection

- KInspector.Core/DatabaseService.cs
- KInspector.Core/IDatabaseService.cs
- KInspector.Modules/Helpers/StrongTypedInfos/SimpleBaseInfo.cs
- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Scripts/PageNotFoundsModule.sql
Adds to the results of the module **Not found errors (404)** the column **Event Last Date** which is useful to know, as there could be a block of page not founds that ended shortly after it began.
Configure KInspector to point to a Kentico instance's database and file system. 
Run the module **Not found errors (404)**.
> Page not founds module revisions

- KenticoInspector.Core/Constants/ReportResultsStatus.cs
- KenticoInspector.Core/Constants/ReportResultsType.cs
- KenticoInspector.Core/KenticoInspector.Core.csproj
- KenticoInspector.Core/Models/ReportResults.cs
- KenticoInspector.Reports.Tests/ApplicationRestartAnalysisTests.cs
- KenticoInspector.Reports.Tests/ClassTableValidationTests.cs
- KenticoInspector.Reports.Tests/DatabaseConsistencyCheckTests.cs
- KenticoInspector.Reports/ApplicationRestartAnalysis/Report.cs
- KenticoInspector.Reports/ClassTableValidation/Report.cs
- KenticoInspector.Reports/DatabaseConsistencyCheck/Report.cs
Use enums instead of strings for report results type and report results status. This reduces chance of error and avoid lots of "ToString()" on the enums
> Use enums instead of strings for report results type+status

- KenticoInspector.Core/AbstractReport.cs
- KenticoInspector.Core/Services/Interfaces/IReportMetadataService.cs
- KenticoInspector.Infrastructure/Services/ReportMetadataService.cs
Fixes #308
This should do the following:
- Load default metadata YAML when the current culture metadata YAML does not exist
- Load non-default (non-en-US) YAML metadata, merge if it is partial, as long as it matches the structure of the model.
> Issue 308 metadata service loading default language

- .github/workflows/dotnet.yml
- KenticoInspector.Actions/KenticoInspector.Actions.csproj
- KenticoInspector.Core.Tests/KenticoInspector.Core.Tests.csproj
- KenticoInspector.Core/Converters/VersionListConverter.cs
- KenticoInspector.Core/Converters/VersionObjectConverter.cs
- KenticoInspector.Core/Helpers/DirectoryHelper.cs
- KenticoInspector.Core/KenticoInspector.Core.csproj
- KenticoInspector.Core/Models/InstanceDetails.cs
- KenticoInspector.Core/Modules/IModule.cs
- KenticoInspector.Core/Tokens/TokenExpressionResolver.cs
- KenticoInspector.Infrastructure.Tests/KenticoInspector.Infrastructure.Tests.csproj
- KenticoInspector.Infrastructure/KenticoInspector.Infrastructure.csproj
- KenticoInspector.Reports.Tests/KenticoInspector.Reports.Tests.csproj
- KenticoInspector.Reports/KenticoInspector.Reports.csproj
- KenticoInspector.WebApplication/Controllers/ActionsController.cs
- KenticoInspector.WebApplication/Controllers/InstancesController.cs
- KenticoInspector.WebApplication/Controllers/ReportsController.cs
- KenticoInspector.WebApplication/KenticoInspector.WebApplication.csproj
- KenticoInspector.WebApplication/Startup.cs
- README.md
The purpose of this PR is to add a minimum viable replacement for AppVeyor Build test using GitHub Actions Workflow
As part of the implementation, several issues were encountered that had to be addressed.
- The .NET Core 2.2 compatibility with Actions Workflow
- Resolved by upgrade to .NET 8
- Packages with bugs when used in .NET 8
- Resolved by upgrading:
- Autofac
- SqlClient
- JSON serialization behaviour has changed.
- Resolved by implementing missing converters.
Verify that project builds, reports execute and conduct code review.
For your reference, the GitHub Action Workflow has been tested on a mirror pull request on forked repository:
https://github.com/JosefDvorak/KInspector/pull/3
> Add GitHub Actions & Upgrade to .NET 8
