Kentico/KInspector

- KInspector.Modules/Modules/Content/AttachmentsBySizeModule.cs
- KInspector.Modules/Modules/Content/TreeNodeChildrenModule.cs
- KInspector.Modules/Modules/Content/WebPartColumnsModule.cs
- KInspector.Modules/Modules/Content/WebPartsInTemplatesAndTransformationsModule.cs
- KInspector.Modules/Modules/EventLog/ApplicationRestartsModule.cs
- KInspector.Modules/Modules/EventLog/EventLogErrorsModule.cs
- KInspector.Modules/Modules/EventLog/PageNotFoundsModule.cs
- KInspector.Modules/Modules/OnlineMarketing/OMContactGroupsWithManualMacro.cs
- KInspector.Modules/Modules/OnlineMarketing/OMNewslettersWithoutQueue.cs
- KInspector.Modules/Modules/OnlineMarketing/OMTablesSize.cs
- KInspector.Modules/Modules/Setup/SmtpServersSetupModule.cs
- KInspector.Modules/Modules/Setup/StagingServersSetupModule.cs
- KInspector.Modules/Modules/Setup/WebFarmServersSetupModule.cs
Some of the modules had a really bad description. I tried to write a better one for those I know what they are doing.
Please check the descriptions that it makes sense to you. Thank you :pray:
> Improve description of certain modules

- KInspector.sln
- README.md
I've added _Get the application_ section and rewrote a little bit an introduction.
It needs a TW review anyway.
> Improve README

- KInspector.Modules/KInspector.Modules.csproj
- KInspector.Modules/Modules/Content/PageTypeAssignedToSiteModule.cs
- KInspector.Modules/Scripts/PageTypeAssignedToSiteModule.sql
Implementation of #23 
Note: I wrote the SQL script as a simple SELECT statement instead of CURSOR based statement.
> Add 'Page type is assigned to a site' module

- KInspector.Web/App.config
Fix for the issue #34. I've tested it and it really works.
> Enable loading blocked assemblies

- KInspector.Modules/KInspector.Modules.csproj
- KInspector.Modules/Modules/Security/UsersWithPlaintextPasswordsModule.cs
- KInspector.Modules/Scripts/UsersWithPlaintextPasswordsModule.sql
Fixes #22.Shows a list of users with plaintext passwords.
> Add detection of users with plaintext passwords

- KInspector.Modules/Modules/Content/AttachmentsBySizeModule.cs
- KInspector.Modules/Scripts/AttachmentsBySizeModule.sql
Fixed for version 9 and it is also working for v6 and 7
> Fix Attachments by size module for v6,7,9

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/Content/WebPartsInTemplatesAndTransformationsModule.cs
- KInspector.Modules/Modules/Content/WebPartsInTransformationsModule.cs
- KInspector.Modules/Scripts/WebPartsInTemplatesAndTransformationsModule.sql
- KInspector.Modules/Scripts/WebPartsInTransformationsModule.sql
I've fixed it to version 9 and it is working also for version 6 and 7 without any problem.
> Fix WP in T&T module for versions 6,7,9

- KInspector.Web/FrontEnd/CSS/style.css
I came up with a solution for header cells which as it seems has already been applied to normal <td>s :)
Fixes #10
> Fixes #10 (Solve problem with long and wide tables)

- KInspector.Modules/Modules/Content/PageTypeAssignedToSiteModule.cs
- KInspector.Modules/Scripts/PageTypeAssignedToSiteModule.sql
> Add support for v9 for PageTypeAssignedToSiteModule

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/Security/PasswordPolicyModule.cs
- KInspector.Modules/Scripts/PasswordPolicy.sql
> Added module to check password policy settings

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/Security/SslInAdminstrationModule.cs
- KInspector.Modules/Scripts/SslInAdministration.sql
Fixes #18 : Added new module and SQL script that checks if SSL is enabled for the administrative interface.
> Fixes #18 : SSL in administration

- KInspector.Modules/Modules/Security/SslInAdminstrationModule.cs
Fixed up namespace in module and updated the method signature.
> Fixes #18 : SSL in administration module error

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/packages.config
This version fixes issues with the latest version (43) of Firefox browser.
> Update Selenium driver to the latest version

- KInspector.Modules/Kentico.KInspector.Modules.csproj
It wasn't added into the project and thus it wasn't copied correctly to the bin location.
> Fix flood protection module script

- KInspector.Modules/Modules/General/PagesAnalyzerModule.cs
- KInspector.Modules/Modules/General/SiteMapModule.cs
- KInspector.Modules/Scripts/PagesAnalyzerModule.sql
- KInspector.Modules/Scripts/SiteMapModule.sql
Extends PagesAnalyzerModule by adding column that tells whether there are any images without alt attribute on a page.
Extends Sitemap module by adding two columns for SEO metadata. Shows whether page has these metatags defined or inherits them from parent.
> Adds 2 features to KInspector modules

- KInspector.Modules/Export/Modules/ExportDocx.cs
- KInspector.Modules/Export/Modules/ExportXlsx.cs
- KInspector.Modules/Export/Modules/ExportXml.cs
- KInspector.Modules/Export/Modules/ExportXmlExtensions.cs
- KInspector.Web/FrontEnd/index.html
- KInspector.Web/WebAPI/Controllers/ExportController.cs
Bug fixes:
https://github.com/Kentico/KInspector/commit/a8d4c87f015efddf95935aaf9538fe93af8ce63f Fix incorrect xlsx export of DataSet (ListOfTables) results
https://github.com/Kentico/KInspector/commit/11f75a4facb64f78b38da3087c69e18d5221f4dd Fix module list to export name uniqueness check
Improvements:
https://github.com/Kentico/KInspector/commit/197140724aa3ac98f35e92396fa2ca54b60cb210  Add Module description to export reports sumary
https://github.com/Kentico/KInspector/commit/bb53d51bfc3e682439efcb231a95d20d43939cac  Add table headers for DataSet docx export
> Export improvements and bugfixes

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/Security/ClickJackingModule.cs
> Resolves #15 - Implement a ClickJacking protection detection module

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/Content/UnusedPageTypesModule.cs
- KInspector.Modules/Modules/Content/UnusedTemplatesModule.cs
- KInspector.Modules/Scripts/UnusedPageTypesModule.sql
- KInspector.Modules/Scripts/UnusedTemplatesModule.sql
Adds modules for finding unused templates and page types
> Add unused templates and  page types modules

- KInspector.Modules/Modules/Content/UnusedTemplatesModule.cs
Expands supported versions for unused templates module
> Unused templates

- KInspector.Modules/Modules/Security/SecurityAppSettingsModule.cs
- Updates some text to make it clearer what is checked
- Added check for CMSHashStringSalt
- Added check fro SA in DB connection
> Security settings web config

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/Security/TransformationAnalyzerModule.cs
- KInspector.Modules/Scripts/TransformationAnalyzerModule-GetDataWhereIn-KI_ClassNames.sql
- KInspector.Modules/Scripts/TransformationAnalyzerModule-GetDataWhereIn-KI_TransformationList.sql
- KInspector.Modules/Scripts/TransformationAnalyzerModule-Initialize-KI_ClassNames.sql
- KInspector.Modules/Scripts/TransformationAnalyzerModule-Initialize-KI_TransformationList.sql
- KInspector.Modules/Scripts/TransformationAnalyzerModule-PageTemplateWebParts.sql
- KInspector.Modules/Scripts/TransformationAnalyzerModule-TransformationCodes-Pre.sql
- KInspector.Modules/Scripts/TransformationAnalyzerModule-TransformationCodes.sql
> Fixes broken transformation analyzer

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/General/DisabledWebPartAnalyzer.cs
- KInspector.Modules/Modules/Security/DisabledWebPartAnalyzer.cs
- KInspector.Modules/Scripts/DisabledWebPartAnalyzerModule.sql
Dear all,
Hopes this helps.
This is my first PR so feedback is well appreciated.
> Fixes #7 "Check for disabled web parts"

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/General/ClassTableValidation.cs
- KInspector.Modules/Scripts/ClassTableValidationClasses.sql
- KInspector.Modules/Scripts/ClassTableValidationTables.sql
The new module compares entries in CMS_Class to tables in Kentico database, to determine if there are any missing.
> Adds Class table validation module

- KInspector.Modules/Modules/Content/WorkflowConsistencyModule.cs
Fix the bug with workflow consistency, it also has backward compability. https://github.com/Kentico/KInspector/issues/160
> Fixes #160

- KInspector.Modules/Modules/Content/WorkflowConsistencyModule.cs
> Workflow XML parsed using ClassName instead of TableName and covers special cases

- KInspector.Modules/Kentico.KInspector.Modules.csproj
- KInspector.Modules/Modules/EventLog/EventLogSizeModule.cs
- KInspector.Modules/Modules/Security/PasswordFormatModule.cs
- KInspector.Modules/Scripts/EventLogSizeModule.sql
- KInspector.Modules/Scripts/PasswordFormat.sql
Re-adds some checks that were removed prematurely
> Adds event log size and password format checks back in

- KenticoInspector.Reports/ApplicationRestartAnalysis/Scripts.cs
- KenticoInspector.Reports/ClassTableValidation/Scripts.cs
- KenticoInspector.Reports/DatabaseConsistencyCheck/Scripts.cs
Refactors script constants for better consistency.
> Refactor script constants to extract base directory

- KenticoInspector.WebApplication/ClientApp/src/api/index.js
- KenticoInspector.WebApplication/ClientApp/src/components/instance-connect-form-manual.vue
- KenticoInspector.WebApplication/ClientApp/src/store/modules/instances.js
> Fixes #247

- README.md
> Initial updates to README for V4

- KenticoInspector.Core/Constants/ReportTags.cs
- KenticoInspector.Reports/ApplicationRestartAnalysis/Report.cs
- KenticoInspector.Reports/ClassTableValidation/Report.cs
- KenticoInspector.Reports/DatabaseConsistencyCheck/Report.cs
Implements #254 converting magic string of report tags to constants.
> Tags to constants

- KenticoInspector.Core/Constants/ReportTags.cs
- KenticoInspector.Core/Helpers/UriHelper.cs
- KenticoInspector.Infrastructure/Helpers/UriHelper.cs
- KenticoInspector.Reports.Tests/DatabaseTableSizeAnalysisTest.cs
- KenticoInspector.Reports.Tests/MockHelpers/MockInstances.cs
- KenticoInspector.Reports.Tests/RobotsConfigurationSummaryTest.cs
- KenticoInspector.Reports/DatabaseTableSizeAnalysis/DatabaseTableSizeResult.cs
- KenticoInspector.Reports/DatabaseTableSizeAnalysis/GetTop25LargestTables.sql
- KenticoInspector.Reports/DatabaseTableSizeAnalysis/Report.cs
- KenticoInspector.Reports/DatabaseTableSizeAnalysis/Scripts.cs
- KenticoInspector.Reports/KenticoInspector.Reports.csproj
- KenticoInspector.Reports/RobotsConfigurationSummary/Constants.cs
- KenticoInspector.Reports/RobotsConfigurationSummary/Report.cs
- KenticoInspector.WebApplication/ClientApp/package-lock.json
- KenticoInspector.WebApplication/KenticoInspector.WebApplication.csproj
Which issue does this fix? Fixes #235 
If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?
If manual testing is required, what are the steps?
> Migrate issue 235

- KenticoInspector.Reports/ContentTreeConsistencyAnalysis/Report.cs
> Add status handling

- appveyor-dev.yml
- appveyor-release.yml
> Split into alternative ymls for different build configs

- appveyor-release.yml
Trying to make AppVeyor automatically deploy to GH releases.
> Add deploy config for releases

- KenticoInspector.Core/KenticoInspector.Core.csproj
- KenticoInspector.Infrastructure/KenticoInspector.Infrastructure.csproj
- KenticoInspector.Reports.Tests/KenticoInspector.Reports.Tests.csproj
- KenticoInspector.Reports/KenticoInspector.Reports.csproj
- KenticoInspector.WebApplication/KenticoInspector.WebApplication.csproj
Enables CI to inject versions into the DLLs
> Add version tags for CI to inject value

- .github/workflows/dotnet-desktop.yml
Which issue does this fix? Fixes #`issue number`
If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?
If manual testing is required, what are the steps?
> add action

- Directory.build.props
- README.md
- docs/Usage-Guide.md
- src/KInspector.Blazor/Components/Instances/NewInstanceModal.razor
- src/KInspector.Core/Scripts/GetCmsSettings.sql
- src/KInspector.Infrastructure/Models/Data/CmsSettingsKey.cs
- src/KInspector.Infrastructure/Services/VersionService.cs
- src/KInspector.Reports/ApplicationRestartAnalysis/Report.cs
- src/KInspector.Reports/DatabaseConsistencyCheck/Report.cs
- src/KInspector.Reports/DatabaseTableSizeAnalysis/Report.cs
Resolves #`386`
Adds support for Xperience by Kentico reports and marks known supported reports as compatible.
- ~~[ ] Automated tests have been added~~
- ~~[ ] Tests are passing~~
No specific tests. Run website and test
> Xbk reports
